apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-vector-config
  namespace: {{ include "tensor-fusion.namespace" . }}
data:
  vector.yaml: |
    sources:
      metrics:
        type: file
        data_dir: /logs
        include:
          - /logs/metrics.log
      
      controller_metrics:
        type: prometheus_scrape
        endpoints:
          - http://localhost:9000/metrics

    transforms:
      parse_influx:
        type: remap
        inputs:
          - metrics
        source: |
          . = parse_influxdb!(.message)
          
      prepare_metrics:
        type: remap
        inputs:
          - parse_influx
        source: |
          .namespace = "tf"
          .tags.nodeName = "${NODE_NAME}"
      
      log_to_metric:
        type: log_to_metric
        inputs:
          - prepare_metrics
        all_metrics: true
        metrics: []
    sinks:
      sink_greptimedb_hypervisor_metrics:
        type: greptimedb_metrics
        inputs:
          - log_to_metric
        new_naming: false
        endpoint: {{ .Values.hypervisor.greptimedbEendpoint }}

      sink_greptimedb_controller_metrics:
        type: prometheus_remote_write
        inputs:
          - controller_metrics
        endpoint: http://{{ .Values.hypervisor.greptimedbEendpoint }}/v1/prometheus/write?db=public
