# permissions for end users to edit gpunodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tensor-fusion-operator
    app.kubernetes.io/managed-by: kustomize
  name: gpunode-editor-role
rules:
- apiGroups:
  - tensor-fusion.ai.tensor-fusion.ai
  resources:
  - gpunodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tensor-fusion.ai.tensor-fusion.ai
  resources:
  - gpunodes/status
  verbs:
  - get
